Repository Barbapapazes/esteban-soubiran.site, pull requests merged in 2022-10, with the labels that each got.

#301 fix: update navigation
  components/organisms/TheHeader.vue
Labels: bug

#297 feat: create sitemap
  package.json
  pnpm-lock.yaml
  server/routes/sitemap.xml.ts
Labels: enhancement

#302 feat: add home link in header
  app.vue
  components/organisms/TheHeader.vue
  content/index.md
  public/favicon.ico
Labels: enhancement

#304 feat: add borderq in bg
  app.vue
Labels: enhancement

#305 fix: use navigation from useContent in footer
  components/organisms/TheFooter.vue
Labels: bug

#314 feat: create github link
  components/content/atoms/GitHubLink.vue
  content/articles/example.md
Labels: enhancement

#313 feat: create detail component
  components/content/molecules/Detail.vue
  content/articles/example.md
Labels: enhancement

#312 feat: add page transition
  app.vue
  layouts/default.vue
Labels: enhancement

#311 fix: update schema
  app.vue
Labels: bug

#315 fix: detail title color
  components/content/molecules/Detail.vue
Labels: bug

#318 feat: create expericence
  components/content/atoms/AppSection.vue
  components/content/molecules/ExperienceItem.vue
  components/content/organisms/ExperienceList.vue
  content/experience/stage.md
  content/index.md
  pnpm-lock.yaml
Labels: enhancement

#321 chore: update dependencies
  .gitignore
  .yarn/releases/yarn-3.2.4.cjs
  .yarnrc.yml
  package.json
  pnpm-lock.yaml
  yarn.lock
Labels: dependencies

#322 chore: move to tailwind css
  components/atoms/AppLink.vue
  layouts/article.vue
  nuxt.config.ts
  package.json
  tailwind.config.js
  windi.config.ts
  yarn.lock
Labels: dependencies

#320 feat: create home pictures
  components/content/organisms/ExperienceList.vue
  components/content/organisms/HomePictures.vue
  content/index.md
  public/images/home/1.webp
  public/images/home/2.webp
  public/images/home/3.webp
  public/images/home/4.webp
  public/images/home/5.webp
Labels: enhancement

#331 refactor: projects
  components/atoms/AppGrid.vue
  components/atoms/AppSection.vue
  components/atoms/CardDate.vue
  components/content/organisms/ArticlesList.vue
  components/content/templates/Articles.vue
  components/content/templates/Home.vue
  components/content/templates/Projects.vue
  components/molecules/ProjectCard.vue
  components/organisms/MainHeader.vue
  components/organisms/ProjectsList.vue
  content/1.about/index.md
  content/2.projects/example.md
  content/2.projects/index.md
  content/3.articles/example.md
  content/3.articles/index.md
  content/4.experience/stage.md
  content/articles/index.md
Labels: enhancement

#332 refactor: articles
  components/atoms/CardDate.vue
  components/content/templates/Articles.vue
  components/molecules/ArticleCard.vue
  components/molecules/ProjectCard.vue
  components/organisms/ArticlesList.vue
  components/organisms/ProjectsList.vue
  content/3.articles/index.md
Labels: enhancement
